WebApplication2/Models/Product.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace WebApplication2.Models
{
    public class Product
    {
        [Key]
        public string Id { get; set; }
        public string ProductName { get; set; }
        public string ProductDescription { get; set; }
        public string ProductImage { get; set; }
        public string ProductPath { get; set; }
        public Decimal ProductPrice { get; set; }
        public string ProductPreviewLink { get; set; }
        public string Notes { get; set; }
        public DateTime CreatedOn { get; set; }
        public bool IsActive { get; set; }
    }

    public class Purchase
    {
        [Key]
        public string Id { get; set; }
        public string ProductId { get; set; }
        public decimal ProductPrice { get; set; }
        public decimal PromotionalPrice { get; set; }
        public decimal Discount { get; set; }
        public int Validity { get; set; }
        public DateTime CreatedOn { get; set; }
        public string CreatedBy { get; set; }
    }
}

WebApplication2/Controllers/PaymentController.cs
using PayPal.Api;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebApplication2.Models;

namespace WebApplication2.Controllers
{
    public class PaymentController : Controller
    {
        // GET: Payment
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult PaymentWithPaypal(string Cancel = null)
        {
            //getting the apiContext  
            APIContext apiContext = PaypalConfiguration.GetAPIContext();
            try
            {
                //A resource representing a Payer that funds a payment Payment Method as paypal  
                //Payer Id will be returned when payment proceeds or click to pay  
                string payerId = Request.Params["PayerID"];
                if (string.IsNullOrEmpty(payerId))
                {
                    //this section will be executed first because PayerID doesn't exist  
                    //it is returned by the create function call of the payment class  
                    // Creating a payment  
                    // baseURL is the url on which paypal sendsback the data.  
                    string baseURI = Request.Url.Scheme + "://" + Request.Url.Authority + "/Home/PaymentWithPayPal?";
                    //here we are generating guid for storing the paymentID received in session  
                    //which will be used in the payment execution  
                    var guid = Convert.ToString((new Random()).Next(100000));
                    //CreatePayment function gives us the payment approval url  
                    //on which payer is redirected for paypal account payment  
                    var createdPayment = this.CreatePayment(apiContext, baseURI + "guid=" + guid, "","","","","","");
                    //get links returned from paypal in response to Create function call  
                    var links = createdPayment.links.GetEnumerator();
                    string paypalRedirectUrl = null;
                    while (links.MoveNext())
                    {
                        Links lnk = links.Current;
                        if (lnk.rel.ToLower().Trim().Equals("approval_url"))
                        {
                            //saving the payapalredirect URL to which user will be redirected for payment  
                            paypalRedirectUrl = lnk.href;
                        }
                    }
                    // saving the paymentID in the key guid  
                    Session.Add(guid, createdPayment.id);
                    return Redirect(paypalRedirectUrl);
                }
                else
                {
                    // This function exectues after receving all parameters for the payment  
                    var guid = Request.Params["guid"];
                    var executedPayment = ExecutePayment(apiContext, payerId, Session[guid] as string);
                    //If executed payment failed then we will show payment failure message to user  
                    if (executedPayment.state.ToLower() != "approved")
                    {
                        return View("FailureView");
                    }
                }
            }
            catch (Exception ex)
            {
                return View("FailureView");
            }
            //on successful payment, show success page to user.  
            return View("SuccessView");
        }
        private PayPal.Api.Payment payment;
        private Payment ExecutePayment(APIContext apiContext, string payerId, string paymentId)
        {
            var paymentExecution = new PaymentExecution()
            {
                payer_id = payerId
            };
            this.payment = new Payment()
            {
                id = paymentId
            };
            return this.payment.Execute(apiContext, paymentExecution);
        }
        private Payment CreatePayment(APIContext apiContext, string redirectUrl, string ProductName, string currency, 
            string price, string quantity, string sku, string productId)
        {
            redirectUrl = "https://localhost:44321/products/purchasecompletion/" + productId;
            //create itemlist and add item objects to it  
            var itemList = new ItemList()
            {
                items = new List<Item>()
            };
            //Adding Item Details like name, currency, price etc  
            itemList.items.Add(new Item()
            {
                name = ProductName,
                currency = currency,
                price = price,
                quantity = quantity,
                sku = sku
            });
            var payer = new Payer()
            {
                payment_method = "paypal"
            };
            // Configure Redirect Urls here with RedirectUrls object  
            var redirUrls = new RedirectUrls()
            {
                cancel_url = redirectUrl + "&Cancel=true",
                return_url = redirectUrl
            };
            // Adding Tax, shipping and Subtotal details  
            var details = new Details()
            {
                tax = "0",
                shipping = "0",
                subtotal = "0"
            };
            //Final amount with details  
            var amount = new Amount()
            {
                currency = currency,
                total = price, // Total must be equal to sum of tax, shipping and subtotal.  
                details = details
            };
            var transactionList = new List<Transaction>();
            // Adding description about the transaction  
            transactionList.Add(new Transaction()
            {
                description = "Transaction description",
                invoice_number = "your generated invoice number", //Generate an Invoice No  
                amount = amount,
                item_list = itemList
            });
            this.payment = new Payment()
            {
                intent = "sale",
                payer = payer,
                transactions = transactionList,
                redirect_urls = redirUrls
            };
            // Create a payment using a APIContext  
            return this.payment.Create(apiContext);
        }
    }
}

WebApplication2/Controllers/ProductsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebApplication2.Models;
using WebApplication2.Services;
using Microsoft.AspNet.Identity;
using System.IO;

namespace WebApplication2.Controllers
{
    public class ProductsController : Controller
    {
        ApplicationDbContext db = new ApplicationDbContext();
        private ProductService productService;
        private StripeSettings stripeSettings;
        private StripeService stripeService;
        public ProductsController()
        {
            productService = new ProductService();
            stripeSettings = new StripeSettings();
            
        }
        // GET: Products
        public ActionResult Index()
        {
            List<Product> products = productService.GetAllProduct();

            return View(products);
        }

        [Authorize]
        public ActionResult PurchaseCompletion(string id)
        {
            return View(productService.GetProduct(id));
        }

        [Authorize]
        public FileResult DownloadFile(string id)
        {
            string userId = User.Identity.GetUserId();
            var purchases = db.UserProducts.Where(m => m.ProductId == id && m.UserId == userId).FirstOrDefault();

            if (purchases == null)
                return null;
            var product = db.Products.Where(m => m.Id == id).FirstOrDefault();
            product.ProductPath = "";
            string fullPath = Server.MapPath("~/" + product.ProductPath);

            byte[] fileBytes = System.IO.File.ReadAllBytes(fullPath);
            string fileName = Path.GetFileName(fullPath);
            return File(fileBytes, System.Net.Mime.MediaTypeNames.Application.Octet, fileName);
        }

        [Authorize]
        [AllowAnonymous]
        public ActionResult ProductDetails(string id)
        {
            string userName = "";
            string userId = "";
            ViewBag.IsPurchased = false;
            try
            {
                userName = User.Identity.GetUserName();
                userId = User.Identity.GetUserId();                
                var purchases = db.UserProducts.Where(m => m.ProductId == id && m.UserId == userId).FirstOrDefault();

                if (purchases != null)
                    ViewBag.IsPurchased = true;
            }
            catch (Exception)
            {

                throw;
            }

            return View(productService.GetProduct(id));
        }

        [Authorize]
        [HttpGet]
        public ActionResult Payment(string id)
        {
            string userId = User.Identity.GetUserId();

            var product = productService.GetProduct(id);
            stripeService = new StripeService("usd", Convert.ToInt64(product.ProductPrice), product.ProductName);
            StripePaymentDetails stripePaymentDetails = new StripePaymentDetails();
            stripePaymentDetails.Amount = Convert.ToInt64(product.ProductPrice) * 100;
            stripePaymentDetails.Desc = product.ProductName;
            stripePaymentDetails.ProductId = id;
            stripePaymentDetails.PublishedKey = "pk_test_Qa9P6sFaNLywMh8qpahQkOyT";

            Purchase purchase = new Purchase();
            purchase.CreatedBy = User.Identity.GetUserId();
            purchase.CreatedOn = DateTime.UtcNow;
            purchase.Id = Guid.NewGuid().ToString();
            purchase.ProductId = id;
            purchase.ProductPrice = product.ProductPrice;
            purchase.Validity = 365;

            UserProducts userProducts = new UserProducts();
            userProducts.Id = Guid.NewGuid().ToString();
            userProducts.UserId = userId;
            userProducts.ProductId = product.Id;
            userProducts.CreatedOn = DateTime.UtcNow;
            userProducts.ValidForDays = 365;

            db.UserProducts.Add(userProducts);
            db.Purchases.Add(purchase);
            db.SaveChanges();

            return View(stripePaymentDetails);
        }

        [Authorize]
        public ActionResult CheckoutFromCart()
        {
            string userId = User.Identity.GetUserId();
            List<CartItemModels> list = (List<CartItemModels>)Session["cart"];
            CheckoutFromCartModels checkoutFromCartModels = new CheckoutFromCartModels();
            string itemName = "";
            decimal totalPrice = 0;
            if (list != null || list.Count() > 0)
            {
                foreach (var item in list)
                {
                    Purchase purchase = new Purchase();
                    purchase.CreatedBy = User.Identity.GetUserId();
                    purchase.CreatedOn = DateTime.UtcNow;
                    purchase.Id = Guid.NewGuid().ToString();
                    purchase.ProductId = item.ProductId;
                    purchase.ProductPrice = item.ProductPrice;
                    purchase.Validity = 365;

                    UserProducts userProducts = new UserProducts();
                    userProducts.Id = Guid.NewGuid().ToString();
                    userProducts.UserId = userId;
                    userProducts.ProductId = item.ProductId;
                    userProducts.CreatedOn = DateTime.UtcNow;
                    userProducts.ValidForDays = 365;

                    db.UserProducts.Add(userProducts);
                    db.Purchases.Add(purchase);

                    checkoutFromCartModels.CartItems.Add(item);
                    itemName += item.ProductName + ", ";
                    totalPrice += item.ProductPrice;
                }
            }
            checkoutFromCartModels.Items = itemName;
            checkoutFromCartModels.TotalPrice = totalPrice;
            return View(checkoutFromCartModels);
        }

        //[Authorize]
        //[HttpPost]
        //public ActionResult Payment(string stripeEmail, string stripeToken)
        //{
        //    stripeService.Charge(stripeEmail, stripeToken);
        //    return View();
        //}

        [Authorize]
        public ActionResult BuyProduct(string id)
        {
            return View(productService.GetProduct(id));
        }

        public ActionResult EatingDisorder()
        {

            return View();
        }

        public ActionResult Webinar()
        {
            return View();
        }
    }
}

WebApplication2/Controllers/WebinarController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WebApplication2.Controllers
{
    public class WebinarController : Controller
    {
        // GET: Webinar
        public ActionResult Index()
        {
            return View();
        }
    }
}

WebApplication2/Views/Products/CheckoutFromCart.cshtml
@model WebApplication2.Models.CheckoutFromCartModels

@{
    ViewBag.Title = "CheckoutFromCart";
    Layout = "~/Views/Shared/_MasterLayout.cshtml";
}



<div class="section-full bg-white content-inner">
    <div class="container">
        <div class="section-content">
            <div class="card-container">
                <div class="row">
                    <p style="margin-left:20px;font-size:24px;color:black;"><strong>Pay With</strong></p>
                    <div class="rdx-accordion bg-title no-cover faq-block col-md-12 col-lg-12" id="accordion5">
                        <div class="panel">
                            <div class="acod-head">
                                <h5 class="acod-title"> <a data-toggle="collapse" href="#collapseOne5"><i class="fa  fa-circle-o"></i> Credit or Debit Card</a> </h5>
                            </div>
                            <div id="collapseOne5" class="acod-body collapse show" data-parent="#accordion5">
                                <div class="acod-content">
                                    <label style="font-size:20px;">Amount : $@(Model.TotalPrice)</label><br />
                                    <label style="font-size:56px;">
                                        <i class="fa fa-cc-mastercard"></i>
                                        <i class="fa fa-cc-visa"></i>
                                        <i class="fa fa-cc-amex"></i>
                                    </label><br />
                                </div>
                            </div>
                        </div>
                        <div class="panel">
                            <div class="acod-head">
                                <h5 class="acod-title">
                                    <a data-toggle="collapse" href="#collapseTwo5" class="collapsed">
                                        <i class="fa  fa-circle-o"></i> Paypal
                                    </a>
                                </h5>
                            </div>
                            <div id="collapseTwo5" class="acod-body collapse" data-parent="#accordion5">
                                <div class="acod-content">
                                    <label style="font-size:20px;">Amount : $@(Model.TotalPrice )</label><br />
                                    <label style="font-size:56px;">
                                        <a href="@Url.Action("PaymentWithPaypal", "Payment")">
                                            <i class="fa fa-cc-paypal"></i>
                                        </a>
                                    </label><br />
                                </div>
                            </div>
                        </div>
                    </div>

                    @*<div class="col-md-4"></div>
                        <div class="col-md-2">
                            <form action="/products/PurchaseCompletion/@Model.ProductId" method="post" style="float:right">
                                <script src="//checkout.stripe.com/v2/checkout.js"
                                        class="stripe-button"
                                        data-key="@Model.PublishedKey"
                                        data-description="@Model.Desc"
                                        data-amount="@Model.Amount">
                                </script>
                            </form>
                        </div>
                        <div class="col-md-2">
                            <button class="btn-info" type="button"
                                    style="float:left;min-height:30px;background-image:linear-gradient(#7dc5ee,#008cdd 85%,#30a2e4);
                                            font-family:'Helvetica Neue',Helvetica,Arial,sans-serif;font-weight: bold;
                                            font-size:14px;text-shadow:0 -1px 0 rgba(0,0,0,0.25);box-shadow:inset 0 1px 0 rgba(255,255,255,0.25);
                                            border-radius:4px;">
                                Pay with Paypal
                            </button>
                        </div>
                        <div class="col-md-4"></div>*@
                    @*<div class="text-center col-md-12">
                            <br />
                            *<span class="text-green" >Pay With Card </span>
                            will be processed by <a href="www.stripe.com">
                            <i style="font-size:36px;" class="fa fa-cc-stripe"></i>
                            stripe.com</a>.
                        </div>*@
                </div>
            </div>
        </div>
    </div>
</div>
<style type="text/css">
    .fa-cc-mastercard {
        color: gray;
    }

        .fa-cc-mastercard:hover {
            color: #0a3a82;
        }

    .fa-cc-visa {
        color: gray;
    }

        .fa-cc-visa:hover {
            color: #0157a2;
        }

    .fa-cc-amex {
        color: gray;
    }

        .fa-cc-amex:hover {
            color: #007bc1;
        }

    .fa-cc-paypal {
        color: gray;
    }

        .fa-cc-paypal:hover {
            color: #253b80;
        }
</style>

WebApplication2/Views/Products/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_MasterLayout.cshtml";

}
@*<div class="section-full bg-white content-inner">
    <div class="container">
        <div class="section-content">
            <div class="row">*@
                <!-- inner page banner -->
                <div class="rdx-bnr-inr overlay-black-middle" style="background-image:url(images/background/Education-Mat.jpg);">
                    <div class="container">
                        <div class="rdx-bnr-inr-entry text-center">
                            <p style="font-size:52px;font-weight:700" class="text-white"> Education Materials </p>
                        </div>
                    </div>
                </div>
                <!-- inner page banner END -->
                <!-- Breadcrumb row -->
                @*<div class="row">
                <div class="breadcrumb-row">
                    <div class="container">
                        <ul class="list-inline">
                            <li><a href="#">Home</a></li>
                            <li>Products</li>
                        </ul>
                    </div>
                </div>
            </div>*@
                <!-- Breadcrumb row END -->
                <!-- contact area -->
                <div class="content-area">
                    <!-- Product -->
                    <div class="container">
                        <div class="row">
                            @if (Model != null)
                            {
                                for (int i = 0; i < Model.Count; i++)
                                {
                                    <div class="col-lg-4 col-md-4 col-sm-6 m-b30">
                                        <div class="rdx-box p-a20 border-1 bg-gray">
                                            <div class="rdx-thum-bx rdx-img-overlay1 rdx-img-effect zoom">
                                                <img src="images/product/@Html.Raw(Model[i].ProductImage)" alt="">
                                                <div class="overlay-bx">
                                                    <div class="overlay-icon"> 
                                                        <a href='@Url.Action("Add", "Cart", new {id = Model[i].Id.Trim()})'> 
                                                            <i class="fa fa-cart-plus icon-bx-xs"></i> 
                                                            </a> 
                                                        <a href="javascript:void(0)">
                                                            <i class="fa fa-search icon-bx-xs"></i> 
                                                        </a> 
                                                        <a href="javascript:void(0)"> 
                                                            <i class="fa fa-heart icon-bx-xs"></i>
                                                        </a> 
                                                    </div>
                                                </div>
                                            </div>
                                            <div class="rdx-info p-t20 text-center">
                                                <h4 class="rdx-title m-t0 m-b5 text-uppercase"><a href='@Url.Action("ProductDetails", "Products", new { id = Model[i].Id })'>@Model[i].ProductName</a></h4>
                                                <h4 class="m-b0 font-weight-700 text-black">$@Model[i].ProductPrice </h4>
                                                @*<a href="javascript:void(0)" class="site-button m-t15">Buy Now</a>*@

                                                @Html.ActionLink("Details", "ProductDetails", "Products", new { id = Model[i].Id }, new { @class = "site-button m-t15" })
                                            </div>
                                        </div>
                                    </div>
                                }
                            }
                        </div>
                    </div>
                    <!-- Product END -->
                </div>
                <!-- contact area  END -->


                <br />

                @*<iframe src="https://cdn.flipsnack.com/widget/v2/widget.html?hash=fznarflsc&bgcolor=EEEEEE&t=1546067953"
            width="100%" height="900px" seamless="seamless" scrolling="no" frameBorder="0" allowFullScreen></iframe>*@

            @*</div>
        </div>
    </div>
</div>*@

WebApplication2/Views/Products/Payment.cshtml
@model WebApplication2.Models.StripePaymentDetails

@{
    ViewBag.Title = "Payment";
    Layout = "~/Views/Shared/_MasterLayout.cshtml";
}

<div class="section-full bg-white content-inner">
    <div class="container">
        <div class="section-content">
            <div class="card-container">
                <div class="">
                    <div class="row">
                        <p style="margin-left:20px;font-size:24px;color:black;"><strong>Pay With</strong></p>
                        <div class="rdx-accordion bg-title no-cover faq-block col-md-12 col-lg-12" id="accordion5">
                            <div class="panel">
                                <div class="acod-head">
                                    <h5 class="acod-title"> <a data-toggle="collapse" href="#collapseOne5"><i class="fa fa-circle"></i> Credit or Debit Card</a> </h5>
                                </div>
                                <div id="collapseOne5" class="acod-body collapse show" data-parent="#accordion5">
                                    <div class="acod-content">
                                        <label style="font-size:20px;">Amount : $@(Model.Amount / 100)</label><br />
                                        <label style="font-size:56px;">
                                            <i class="fa fa-cc-mastercard"></i>
                                            <i class="fa fa-cc-visa"></i>
                                            <i class="fa fa-cc-amex"></i>
                                        </label><br />
                                    </div>
                                </div>
                            </div>
                            <div class="panel">
                                <div class="acod-head">
                                    <h5 class="acod-title"> 
                                    <a data-toggle="collapse" href="#collapseTwo5" class="collapsed">
                                        <i class="fa fa-circle"></i> Paypal </a> </h5>
                                </div>
                                <div id="collapseTwo5" class="acod-body collapse" data-parent="#accordion5">
                                    <div class="acod-content">
                                        <label style="font-size:20px;">Amount : $@(Model.Amount / 100)</label><br />
                                        <label style="font-size:56px;">
                                            <i class="fa fa-cc-paypal"></i>
                                            </label><br/>
                                    </div>
                                </div>
                            </div>
                        </div>

                        @*<div class="col-md-4"></div>
                        <div class="col-md-2">
                            <form action="/products/PurchaseCompletion/@Model.ProductId" method="post" style="float:right">
                                <script src="//checkout.stripe.com/v2/checkout.js"
                                        class="stripe-button"
                                        data-key="@Model.PublishedKey"
                                        data-description="@Model.Desc"
                                        data-amount="@Model.Amount">
                                </script>
                            </form>
                        </div>
                        <div class="col-md-2">
                            <button class="btn-info" type="button"
                                    style="float:left;min-height:30px;background-image:linear-gradient(#7dc5ee,#008cdd 85%,#30a2e4);
                                            font-family:'Helvetica Neue',Helvetica,Arial,sans-serif;font-weight: bold;
                                            font-size:14px;text-shadow:0 -1px 0 rgba(0,0,0,0.25);box-shadow:inset 0 1px 0 rgba(255,255,255,0.25);
                                            border-radius:4px;">
                                Pay with Paypal
                            </button>
                        </div>
                        <div class="col-md-4"></div>*@
                        @*<div class="text-center col-md-12">
                                <br />
                                *<span class="text-green" >Pay With Card </span>
                                will be processed by <a href="www.stripe.com">
                                <i style="font-size:36px;" class="fa fa-cc-stripe"></i>
                                stripe.com</a>.
                            </div>*@
                    </div>
                </div>
            </div>
        </div>
    </div>

    <style type="text/css">
        .fa-cc-mastercard {
            color: gray;
        }

            .fa-cc-mastercard:hover {
                color: #0a3a82;
            }

        .fa-cc-visa {
            color: gray;
        }

            .fa-cc-visa:hover {
                color: #0157a2;
            }

        .fa-cc-amex {
            color: gray;
        }

            .fa-cc-amex:hover {
                color: #007bc1;
            }

        .fa-cc-paypal {
            color: gray;
        }

            .fa-cc-paypal:hover {
                color: #253b80;
            }
    </style>

WebApplication2/Views/Products/PurchaseCompletion.cshtml
@model WebApplication2.Models.Product
@{
    ViewBag.Title = "PurchaseCompletion";
    Layout = "~/Views/Shared/_MasterLayout.cshtml";
}
<div class="section-full bg-white content-inner">
    <div class="container">
        <div class="section-content">
            <div class="card-container alert alert-success">
                <div class="text-center">
                    <p style="font-size:24px;">You have successfully purchased the content!</p>
                    <p style="font-size:18px;">
                        <table class="center-block InfoTable">
                            
                                <tr>
                                    <td >Content Name </td>
                                    <td >@Model.ProductName</td>
                                </tr>
                                <tr >
                                    <td >Content Price </td>
                                    <td >$ @Model.ProductPrice</td>
                                </tr>
                        </table>
                    </p>
                    <div class="">
                        <a class="site-button green m-rs"
                           href="~/@Html.Raw(Model.ProductPath)" style="margin-left:40px;">
                            <i class="fa fa-book"></i>Read Now
                        </a>

                        <a class="site-button yellow m-rs"
                           href='@Url.Action("BuyProduct", "Products", new { id=Model.Id})' style="margin-left:40px;">
                            <i class="fa fa-download"></i>Download Now
                        </a>

                        <a class="site-button red m-rs"
                           href='@Url.Action("Index", "Home")' style="margin-left:40px;">
                            <i class="fa fa-home"></i>Return To Home
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<style>
    table.InfoTable {
        border: 1px solid white;
        background-color: #EEEEEE;
        width: 253px;
        text-align: center;
    }

        table.InfoTable td, table.InfoTable th {
            border: 1px solid white;
            padding: 3px 2px;
        }

        table.InfoTable tbody td {
            font-size: 16px;
        }
</style>