WebApplication2/Controllers/AdminController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebApplication2.Models;

namespace WebApplication2.Controllers
{
    [Authorize(Roles = "Administrator")]
    public class AdminController : Controller
    {
        ApplicationDbContext dbContext = new ApplicationDbContext();

        // GET: Admin
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Dashboard()
        {
            AdminDashboardModels adminDashboardModels = new AdminDashboardModels();

            return View (adminDashboardModels);
        }

        public ActionResult Sales()
        {
            var purchases = dbContext.Purchases.Select(m => m).ToList();
            return View(purchases);
        }


        public ActionResult Users()
        {
            var userList = dbContext.UserProfiles.Select(m => m).ToList();

            return View(userList);
        }

        public ActionResult Referrals()
        {
            var userList = dbContext.UserProfiles.Select(m => m).ToList();
            var referred = userList.Where(m => m.ReferredBy != "" || m.ReferredBy != null);
            var notReferred = userList.Where(m => m.ReferredBy == "" || m.ReferredBy == null);
            ReferredUsersList referredUsersList = new ReferredUsersList();
            ReferredUsers referredUsers = new ReferredUsers();
            foreach (var temp in referred)
            {
                referredUsers = new ReferredUsers();
                referredUsers.UserId = temp.Id;
                referredUsers.UserName = string.IsNullOrEmpty(temp.FullName) ? temp.FirstName + " " + temp.LastName : temp.FullName;
                referredUsers.ReferredBy = temp.ReferredBy;
                referredUsers.OwnReferralCode = temp.MyReferralCode;
                referredUsersList.ReferredUsers.Add(referredUsers);
            }

            foreach (var temp in notReferred)
            {
                referredUsers = new ReferredUsers();
                referredUsers.UserId = temp.Id;
                referredUsers.UserName = string.IsNullOrEmpty(temp.FullName) ? temp.FirstName + " " + temp.LastName : temp.FullName;
                referredUsers.ReferredBy = temp.ReferredBy;
                referredUsers.OwnReferralCode = temp.MyReferralCode;
                referredUsersList.NonReferredUsers.Add(referredUsers);
            }
            return View(referredUsersList);
        }

    }
}

WebApplication2/Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebApplication2.Models;
using Microsoft.AspNet.Identity;

namespace WebApplication2.Controllers
{
    public class UserController : Controller
    {
        ApplicationDbContext dbContext = new ApplicationDbContext();
        // GET: User
        public ActionResult Index()
        {
            return View();
        }

        [Authorize]
        [HttpGet]
        public ActionResult Profile()
        {
            string id = User.Identity.GetUserId();
            var userProfile = dbContext.UserProfiles.Where(m => m.Id == id).FirstOrDefault();
            
            return View (userProfile);
        }

        [HttpPost]
        public ActionResult Profile(UserProfile userProfile)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    var tempUserProfile = dbContext.UserProfiles.Where(m => m.Id == userProfile.Id).FirstOrDefault();
                    tempUserProfile.Address = userProfile.Address;
                    tempUserProfile.DateOfBirth = userProfile.DateOfBirth;
                    tempUserProfile.Desc = userProfile.Desc;
                    tempUserProfile.Email = userProfile.Email;
                    tempUserProfile.FirstName = userProfile.FirstName;
                    tempUserProfile.LastName = userProfile.LastName;
                    tempUserProfile.FullName = userProfile.FirstName + " " + userProfile.LastName;
                    tempUserProfile.LicenseNumber = userProfile.LicenseNumber;
                    tempUserProfile.Profession = userProfile.Profession;
                    tempUserProfile.Mobile = userProfile.Mobile;
                    tempUserProfile.UserProfilePic = userProfile.UserProfilePic;

                    dbContext.SaveChanges();
                }
                catch (Exception ex)
                {
                }
            }
            
            return View();
        }

        public ActionResult Dashboard()
        {
            return View ();
        }

        [Authorize]
        public ActionResult MyProducts()
        {
            var userId = User.Identity.GetUserId();
            List<Product> products = new List<Product>();
            var allProducts = dbContext.Products.Select(m => m).ToList();

            var purchasedProducts = dbContext.UserProducts.Where(m => m.UserId == userId).ToList();

            if (purchasedProducts != null && purchasedProducts.Count > 0)
            {
                foreach (var product in purchasedProducts)
                {
                    products.Add(allProducts.Where(m => m.Id == product.ProductId).FirstOrDefault());
                }
            }

            return View(products);
        }
    }
}

WebApplication2/Views/Shared/StarRatingComponent.cshtml
<section class='rating-widget'>

    <!-- Rating Stars Box -->
    <div class='row rating-stars text-center'>
        <ul id='stars'>
            <li class='star' title='Poor' data-value='1'>
                <i class='fa fa-star fa-fw'></i>
            </li>
            <li class='star' title='Fair' data-value='2'>
                <i class='fa fa-star fa-fw'></i>
            </li>
            <li class='star' title='Good' data-value='3'>
                <i class='fa fa-star fa-fw'></i>
            </li>
            <li class='star' title='Excellent' data-value='4'>
                <i class='fa fa-star fa-fw'></i>
            </li>
            <li class='star' title='WOW!!!' data-value='5'>
                <i class='fa fa-star fa-fw'></i>
            </li>
        </ul>
    </div>

</section>

<script type="text/javascript">
    $(document).ready(function () {

        /* 1. Visualizing things on Hover - See next part for action on click */
        $('#stars li').on('mouseover', function () {
            var onStar = parseInt($(this).data('value'), 10); // The star currently mouse on

            // Now highlight all the stars that's not after the current hovered star
            $(this).parent().children('li.star').each(function (e) {
                if (e < onStar) {
                    $(this).addClass('hover');
                }
                else {
                    $(this).removeClass('hover');
                }
            });

        }).on('mouseout', function () {
            $(this).parent().children('li.star').each(function (e) {
                $(this).removeClass('hover');
            });
        });


        /* 2. Action to perform on click */
        $('#stars li').on('click', function () {
            var onStar = parseInt($(this).data('value'), 10); // The star currently selected
            var stars = $(this).parent().children('li.star');

            for (i = 0; i < stars.length; i++) {
                $(stars[i]).removeClass('selected');
            }

            for (i = 0; i < onStar; i++) {
                $(stars[i]).addClass('selected');
            }

            // JUST RESPONSE (Not needed)
            var ratingValue = parseInt($('#stars li.selected').last().data('value'), 10);
            var msg = "";
            if (ratingValue > 1) {
                msg = "Thanks! You rated this " + ratingValue + " stars.";
            }
            else {
                msg = "We will improve ourselves. You rated this " + ratingValue + " stars.";
            }
            responseMessage(msg);

        });


    });


    function responseMessage(msg) {
        
        $('.success-box').fadeIn(200);
        $('.success-box div.text-message').html("<span>" + msg + "</span>");
    }
</script>

<style type="text/css">
    body {
        font-family: "Open Sans", Helvetica, Arial, sans-serif;
        color: #555;
        /*max-width: 680px;*/
        margin: 0 auto;
        padding: 0 20px;
    }

    * {
        -webkit-box-sizing: border-box;
        -moz-box-sizing: border-box;
        box-sizing: border-box;
    }

        *:before, *:after {
            -webkit-box-sizing: border-box;
            -moz-box-sizing: border-box;
            box-sizing: border-box;
        }

    .clearfix {
        clear: both;
    }

    .text-center {
        text-align: center;
    }

    a {
        color: tomato;
        text-decoration: none;
    }

        a:hover {
            color: #2196f3;
        }

    pre {
        display: block;
        padding: 9.5px;
        margin: 0 0 10px;
        font-size: 13px;
        line-height: 1.42857143;
        color: #333;
        word-break: break-all;
        word-wrap: break-word;
        background-color: #F5F5F5;
        border: 1px solid #CCC;
        border-radius: 4px;
    }

    .header {
        padding: 20px 0;
        position: relative;
        margin-bottom: 10px;
    }

        .header:after {
            content: "";
            display: block;
            height: 1px;
            background: #eee;
            position: absolute;
            left: 30%;
            right: 30%;
        }

        .header h2 {
            font-size: 3em;
            font-weight: 300;
            margin-bottom: 0.2em;
        }

        .header p {
            font-size: 14px;
        }



    #a-footer {
        margin: 20px 0;
    }

    .new-react-version {
        padding: 20px 20px;
        border: 1px solid #eee;
        border-radius: 20px;
        box-shadow: 0 2px 12px 0 rgba(0,0,0,0.1);
        text-align: center;
        font-size: 14px;
        line-height: 1.7;
    }

        .new-react-version .react-svg-logo {
            text-align: center;
            max-width: 60px;
            margin: 20px auto;
            margin-top: 0;
        }

    /* Rating Star Widgets Style */
    .rating-stars ul {
        list-style-type: none;
        padding: 0;
        -moz-user-select: none;
        -webkit-user-select: none;
    }

        .rating-stars ul > li.star {
            display: inline-block;
        }

            /* Idle State of the stars */
            .rating-stars ul > li.star > i.fa {
                font-size: 2.5em; /* Change the size of the stars */
                color: #ccc; /* Color on idle state */
            }

            /* Hover state of the stars */
            .rating-stars ul > li.star.hover > i.fa {
                color: #FFCC36;
            }

            /* Selected state of the stars */
            .rating-stars ul > li.star.selected > i.fa {
                color: #FF912C;
            }

</style>

WebApplication2/Views/Shared/_DashboardLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">


    <!-- FAVICONS ICON -->
    <link rel="icon" href="~/images/WT180_LogoGreyText.svg" type="image/x-icon" />
    <link rel="shortcut icon" type="image/x-icon" href="~/images/WT180_LogoGreyText.svg" />

    <title>Wellness Today 180</title>

    <!-- MOBILE SPECIFIC -->
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!--[if lt IE 9]>
    <script src="js/html5shiv.min.js"></script>
    <script src="js/respond.min.js"></script>
    <![endif]-->
    <!-- STYLESHEETS -->
    <link rel="stylesheet" type="text/css" href="~/css/plugins.css">
    <link rel="stylesheet" type="text/css" href="~/css/style.css">
    <link class="skin" rel="stylesheet" type="text/css" href="~/css/skin/skin-3.css">
    <link rel="stylesheet" type="text/css" href="~/css/templete.css">

    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/simple-line-icons/2.4.1/css/simple-line-icons.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:400,700">
    <link href="@Url.Content("~/Content/custom-product-package.css")" rel="stylesheet" type="text/css" />

    <!-- REVOLUTION SLIDER CSS -->
    <link rel="stylesheet" type="text/css" href="~/plugins/revolution/revolution/css/settings.css">
    <link rel="stylesheet" type="text/css" href="~/plugins/revolution/revolution/css/navigation.css">
    <link rel="stylesheet" type="text/css" href="~/css/plugins.css" />
    <link rel="stylesheet" type="text/css" href="~/css/style.css" />
    <link rel="stylesheet" type="text/css" href="~/css/skin/skin-3.css" />
    <link rel="stylesheet" type="text/css" href="~/css/templete.css" />

    <!-- PAGE TITLE HERE -->
    <title>@ViewBag.Title - Wellness Today 180</title>
</head>
<body id="bg">
    <div class="page-wraper">
        <!-- Content -->
        <div class="page-content one-page-layout">
            <div class="sidenav full-page navbar sticky-header onepage" id="mySidenav">
                <div class="logo-header mostion">
                    <a href="index.html">
                        <img src="~/images/WT180_Logo_NoText.svg" alt="">
                        @*<img src="~/images/logo_WT180.png" width="193" height="89" alt="">*@
                    </a>
                </div>
                <a href="javascript:void(0)" class="closebtn bg-primary ">&times;</a>
                <div class="clearfix"></div>
                <div id="myNavbar" style="margin-left:30px;font-size:20px;">
                    @if (Request.IsAuthenticated)
                    {
                        if (User.IsInRole("Administrator"))
                        {
                            <ul class="p-b100 nav">
                                <li>
                                    @Html.ActionLink("Dashboard", "Dashboard", "Admin")
                                </li>
                                <li>
                                    @Html.ActionLink("Sales", "Sales", "Admin")
                                </li>
                                <li>
                                    @Html.ActionLink("Users", "Users", "Admin")
                                </li>
                                <li>
                                    @Html.ActionLink("Referrals", "Referrals", "Admin")
                                </li>
                                <li>
                                    @Html.ActionLink("Return Home", "Index", "Home")
                                </li>
                            </ul>
                        }
                        else
                        {
                            <ul class="p-b100 nav">
                                @*<li>
                                    @Html.ActionLink("Dashboard", "Dashboard", "User")
                                </li>*@
                                <li>
                                    @Html.ActionLink("Profile", "Profile", "User")
                                </li>
                                <li>
                                    @Html.ActionLink("My Products", "Products", "User")
                                </li>
                                <li>
                                    @Html.ActionLink("Return Home", "Index", "Home")
                                </li>
                            </ul>
                        }
                    }

                </div>
                @*<div class="left-footer-menu p-b10">
                        <ul class="list-inline footer-social text-center m-b0">
                            <li><a href="javascript:void(0);" class="fa fa-facebook bg-primary"></a></li>
                            <li><a href="javascript:void(0);" class="fa fa-twitter bg-primary"></a></li>
                            <li><a href="javascript:void(0);" class="fa fa-linkedin bg-primary"></a></li>
                            <li><a href="javascript:void(0);" class="fa fa-google-plus bg-primary"></a></li>
                        </ul>
                    </div>*@
            </div>

            <div id="main" class="">
                <div class="section-full bg-white content-inner">
                    <div class="contant-block">
                        @RenderBody()
                    </div>
                </div>
            </div>
        </div>
        <!-- JavaScript  files ========================================= -->
        <script src="@Url.Content("~/js/jquery.min.js")"></script><!-- JQUERY.MIN JS -->
        <script src="@Url.Content("~/plugins/bootstrap/js/popper.min.js")"></script><!-- BOOTSTRAP.MIN JS -->
        <script src="@Url.Content("~/plugins/bootstrap/js/bootstrap.min.js")"></script><!-- BOOTSTRAP.MIN JS -->
        <script src="@Url.Content("~/plugins/bootstrap-select/bootstrap-select.min.js")"></script><!-- FORM JS -->
        <script src="@Url.Content("~/plugins/bootstrap-touchspin/jquery.bootstrap-touchspin.js")"></script><!-- FORM JS -->
        <script src="@Url.Content("~/plugins/magnific-popup/magnific-popup.js")"></script><!-- MAGNIFIC POPUP JS -->
        <script src="@Url.Content("~/plugins/counter/waypoints.js")"></script><!-- WAYPOINTS JS -->
        <script src="@Url.Content("~/plugins/counter/counterup.min.js")"></script><!-- COUNTERUP JS -->
        <script src="@Url.Content("~/plugins/imagesloaded/imagesloaded.js")"></script><!-- IMAGESLOADED -->
        <script src="@Url.Content("~/plugins/masonry/masonry-3.1.4.js")"></script><!-- MASONRY -->
        <script src="@Url.Content("~/plugins/masonry/masonry.filter.js")"></script><!-- MASONRY -->
        <script src="@Url.Content("~/plugins/owl-carousel/owl.carousel.js")"></script><!-- OWL SLIDER -->
        <script src="@Url.Content("~/js/custom.js")"></script><!-- CUSTOM FUCTIONS  -->
        <script src="@Url.Content("~/js/dz.carousel.js")"></script><!-- SORTCODE FUCTIONS  -->
        <script src="@Url.Content("~/js/dz.ajax.js")"></script><!-- CONTACT JS  -->
        <!-- REVOLUTION JS FILES -->
        <script src="@Url.Content("~/plugins/revolution/revolution/js/jquery.themepunch.tools.min.js")"></script>
        <script src="@Url.Content("~/plugins/revolution/revolution/js/jquery.themepunch.revolution.min.js")"></script>
        <!-- Slider revolution 5.0 Extensions  (Load Extensions only on Local File Systems !  The following part can be removed on Server for On Demand Loading) -->
        <script src="@Url.Content("~/plugins/revolution/revolution/js/extensions/revolution.extension.actions.min.js")"></script>
        <script src="@Url.Content("~/plugins/revolution/revolution/js/extensions/revolution.extension.carousel.min.js")"></script>
        <script src="@Url.Content("~/plugins/revolution/revolution/js/extensions/revolution.extension.kenburn.min.js")"></script>
        <script src="@Url.Content("~/plugins/revolution/revolution/js/extensions/revolution.extension.layeranimation.min.js")"></script>
        <script src="@Url.Content("~/plugins/revolution/revolution/js/extensions/revolution.extension.migration.min.js")"></script>
        <script src="@Url.Content("~/plugins/revolution/revolution/js/extensions/revolution.extension.navigation.min.js")"></script>
        <script src="@Url.Content("~/plugins/revolution/revolution/js/extensions/revolution.extension.parallax.min.js")"></script>
        <script src="@Url.Content("~/plugins/revolution/revolution/js/extensions/revolution.extension.slideanims.min.js")"></script>
        <script src="@Url.Content("~/plugins/revolution/revolution/js/extensions/revolution.extension.video.min.js")"></script>
        <script src="@Url.Content("~/js/rev.slider.js")"></script>

        <script>
            jQuery(document).ready(function () {
                'use strict';
                dz_rev_slider_1();
            });	/*ready*/
        </script>


        @Scripts.Render("~/bundles/jquery")
        @Scripts.Render("~/bundles/bootstrap")
        @*@Scripts.Render("~/bundles/plugins")
            @Scripts.Render("~/bundles/js")*@
        @Styles.Render("~/bundles/css2")
        @RenderSection("scripts", required: false)
</body>
</html>